### ISSUE TITLE
AttributeError: module 'music_trees' has no attribute 'utils'

### ISSUE THREAD

**Issue by loretoparisi** [hugofloresgarcia/music-trees#1]
Hello this was my command,
```
!python -m music_trees.generate \
                --dataset medleydb \
                --name mdb-aug \
                --example_length 1.0 \
                --augment true \
                --hop_length 0.5 \
                --sample_rate 16000 \
```

and outcome

```Global seed set to 42
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/ec2-user/SageMaker/medleydb/medleydb/medleydb/music-trees/music_trees/__init__.py", line 2, in <module>
    from . import utils
  File "/home/ec2-user/SageMaker/medleydb/medleydb/medleydb/music-trees/music_trees/utils/__init__.py", line 2, in <module>
    from . import effects
  File "/home/ec2-user/SageMaker/medleydb/medleydb/medleydb/music-trees/music_trees/utils/effects.py", line 9, in <module>
    import music_trees.utils as utils
AttributeError: module 'music_trees' has no attribute 'utils'
```

**Comment by loretoparisi** [comment]
I have fixed that removing the line

https://github.com/hugofloresgarcia/music-trees/blob/main/music_trees/utils/effects.py#L9

that is actually not needed.
