### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/SageMaker/music-trees/data/mdb-aug'

### ISSUE THREAD

**Issue by loretoparisi** [hugofloresgarcia/music-trees#2]
After fixing the reported issues, I get this error

```Global seed set to 42
/home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:64: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  INST_TAXONOMY = yaml.load(fhandle)
/home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:72: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  MIXING_COEFFICIENTS = yaml.load(fhandle)
/home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:94: UserWarning: The medleydb audio was not found at the expected path: None This module will still function, but without the ability to access any of the audio.
  UserWarning
Global seed set to 42
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/SageMaker/music-trees/music_trees/generate/__main__.py", line 18, in <module>
    generate_data(**vars(args))
  File "/home/ec2-user/SageMaker/music-trees/music_trees/generate/core.py", line 81, in generate_data
    output_dir.mkdir(exist_ok=False)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/SageMaker/music-trees/data/mdb-aug'
```

when running

```
! python -m music_trees.generate \
                --dataset medleydb \
                --name mdb-aug \
                --example_length 1.0 \
                --augment true \
                --hop_length 0.5 \
                --sample_rate 16000 \
```

Is this related to the `augment true` as stated in the docs?
In that case, running with `--augment false`

```
! python -m music_trees.generate \
                --dataset medleydb \
                --name mdb-aug \
                --example_length 1.0 \
                --augment false \
                --hop_length 0.5 \
                --sample_rate 16000 \
```

I get the same error...

**Comment by hugofloresgarcia** [comment]
Hi! Taking a look right now.

**Comment by hugofloresgarcia** [comment]
Hi! What does your directory structure look like? There should be a folder called `data` from where you're running the experiment.

**Comment by hugofloresgarcia** [comment]
However, I can push an easy fix for this to not be a requirement

**Comment by loretoparisi** [comment]
> Hi! What does your directory structure look like? There should be a folder called `data` from where you're running the experiment.

In my notebook I have this structure
<img width="1196" alt="Schermata 2021-11-12 alle 15 38 23" src="https://user-images.githubusercontent.com/163333/141484268-98deb326-e3e3-4249-940f-575c34de7acf.png">

and within `music-trees` I have

<img width="1158" alt="Schermata 2021-11-12 alle 15 38 29" src="https://user-images.githubusercontent.com/163333/141484264-2fbc6194-e449-4e67-a324-ded2e8cefecb.png">


I do not see any `data` folder. How to create it? Thanks.

**Comment by hugofloresgarcia** [comment]
just pushed a fix: 08002c144bb7de800dbcb609a15808ed94fdd557. Could you pull and let me know if it works? Thanks!

**Comment by loretoparisi** [comment]
> just pushed a fix: [08002c1](https://github.com/hugofloresgarcia/music-trees/commit/08002c144bb7de800dbcb609a15808ed94fdd557). Could you pull and let me know if it works? Thanks!

yep!

**Comment by loretoparisi** [comment]
So applied the changes:
```
%set_env MEDLEYDB_PATH=/home/ec2-user/SageMaker/medleydb
! python -m music_trees.generate \
                --dataset mdb \
                --name mdb-aug \
                --example_length 1.0 \
                --augment true \
                --hop_length 0.5 \
                --sample_rate 16000 \
```

and I have some medley db error:

```
env: MEDLEYDB_PATH=/home/ec2-user/SageMaker/medleydb
Global seed set to 42
/home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:64: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  INST_TAXONOMY = yaml.load(fhandle)
/home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:72: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  MIXING_COEFFICIENTS = yaml.load(fhandle)
/home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:94: UserWarning: The medleydb audio was not found at the expected path: None This module will still function, but without the ability to access any of the audio.
  UserWarning
Global seed set to 42
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/librosa/core/audio.py", line 699, in get_duration
    return sf.info(filename).duration
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/soundfile.py", line 438, in info
    return _SoundFileInfo(file, verbose)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/soundfile.py", line 383, in __init__
    with SoundFile(file) as f:
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/media/CHONK/data/MedleyDB/Audio/AimeeNorwich_Flying/AimeeNorwich_Flying_STEMS/AimeeNorwich_Flying_STEM_13.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/SageMaker/music-trees/music_trees/generate/__main__.py", line 18, in <module>
    generate_data(**vars(args))
  File "/home/ec2-user/SageMaker/music-trees/music_trees/generate/core.py", line 87, in generate_data
    file_records = loader_fn()
  File "/home/ec2-user/SageMaker/music-trees/music_trees/generate/mdb.py", line 75, in load_all_filepaths
    dur += librosa.core.get_duration(filename=record['path'])
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/librosa/core/audio.py", line 701, in get_duration
    with audioread.audio_open(filename) as fdesc:
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/audioread/__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/audioread/rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/media/CHONK/data/MedleyDB/Audio/AimeeNorwich_Flying/AimeeNorwich_Flying_STEMS/AimeeNorwich_Flying_STEM_13.wav'
```

I have installed `medleydb` in this way:

```
%cd /home/ec2-user/SageMaker/
! rm -rf medleydb
! git clone https://github.com/marl/medleydb.git
%cd medleydb
!pip install -e .
%set_env MEDLEYDB_PATH=/home/ec2-user/SageMaker/medleydb
%cd /home/ec2-user/SageMaker/
```

**Comment by loretoparisi** [comment]
Ah! I have also fixed this problem with the `OrderedDict`:

```
-from typing import List, OrderedDict, Dict
+from typing import List, Dict
```

here
https://github.com/loretoparisi/music-trees/commit/c3cd93dcf981f8e0ed349603603c97062cc0df5c#diff-40a7c1fea9c24b2a73a86ca1155b4356a9b378e61b1c8f6c07b73cc0e88d9f4d


since `OrderedDict` is imported in the next very line:

```
from collections import OrderedDict
```

**Comment by hugofloresgarcia** [comment]
fixed bfc3e4f4f1614f37eed698d93046c1909ed13f3d! !

**Comment by loretoparisi** [comment]
@hugofloresgarcia thanks! I now can see the folder `mdb-aug` been created, but I do not see any JSON file there. Also I'm getting the error

```
raceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/music-trees/music_trees/generate/__main__.py", line 18, in <module>
    generate_data(**vars(args))
  File "/content/music-trees/music_trees/generate/core.py", line 87, in generate_data
    file_records = loader_fn()
  File "/content/music-trees/music_trees/generate/mdb.py", line 75, in load_all_filepaths
    dur += librosa.core.get_duration(filename=record['path'])
  File "/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py", line 701, in get_duration
    with audioread.audio_open(filename) as fdesc:
  File "/usr/local/lib/python3.7/dist-packages/audioread/__init__.py", line 111, in audio_open
    return BackendClass(path)
  File "/usr/local/lib/python3.7/dist-packages/audioread/rawread.py", line 62, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/media/CHONK/data/MedleyDB/Audio/AimeeNorwich_Flying/AimeeNorwich_Flying_STEMS/AimeeNorwich_Flying_STEM_13.wav'
```

I have put all together in [this](https://colab.research.google.com/drive/18UNmiwIkKOqrvXHmLeFoAlrooVFETrhU?usp=sharing) Colab to make it working with all these fixes.

**Comment by hugofloresgarcia** [comment]
I see you're cloning the medleyDB repo, but have you downloaded the MedleyDB data? The data and the repo are separate. You can download the data here: https://zenodo.org/record/1649325, https://zenodo.org/record/1715175

**Comment by loretoparisi** [comment]
@hugofloresgarcia just to confirm is the audio files from MedleyDB v2 or orignal (v1)? Thanks!

**Comment by hugofloresgarcia** [comment]
We use the audio files from both  MedleyDB v1 and v2.

**Comment by loretoparisi** [comment]
> We use the audio files from both MedleyDB v1 and v2.

Okay so I download both and put all files in the `audio` subfolder?

**Comment by hugofloresgarcia** [comment]
that's correct!

**Comment by loretoparisi** [comment]
@hugofloresgarcia hi Hugo, sorry to bother, I have all the audio, but I'm not sure of the actual dir location where to put them! I can see from the logs this path
```
'/media/CHONK/data/MedleyDB/Audio/AimeeNorwich_Flying/AimeeNorwich_Flying_STEMS/AimeeNorwich_Flying_STEM_13.wav': System error.
```

but which is the root? I have in my root folder
<img width="1231" alt="Schermata 2021-11-19 alle 10 13 46" src="https://user-images.githubusercontent.com/163333/142596963-e01c986e-9f29-4304-82bc-a5c5dda87d78.png">

while in my audio folder (merged with v1 and v2 medley audios) I have a number of subfolders like
```
                           PRE AClassicEducation_NightOwl/
                           PRE AimeeNorwich_Child/
                           PRE AimeeNorwich_Flying/
                           PRE AlexanderRoss_GoodbyeBolero/
                           PRE AlexanderRoss_VelvetCurtain/
                           PRE AmarLal_Rest/
                           PRE AmarLal_SpringDay1/
                           PRE Auctioneer_OurFutureFaces/
                           PRE AvaLuna_Waterduct/
                           PRE BigTroubles_Phantom/
                           PRE BrandonWebster_DontHearAThing/
                           PRE BrandonWebster_YesSirICanFly/
...
```

So now, where I have to move all these audios?
 Thanks a lot!

**Comment by hugofloresgarcia** [comment]
Hi Loreto, 

Thanks so much for helping us externally debug our code!

You should delete  the file: `music_trees/assets/mdb/mdb-files.json`. This file should not be tracked anyway. Fixed this in 5f778b39aa05531183c81529b7f41ed6b362cba6

**Comment by loretoparisi** [comment]
@hugofloresgarcia you are welcome. And what about Medley db audio files root folder? Thanks again.

**Comment by hugofloresgarcia** [comment]
It doesn't matter where your MedleyDB audio files are (mine were under a `./data/` dir), but you have to make sure to set the environment variable `MEDLEYDB_PATH` to the path where your audio files live. For more info, checkout the MedleyDB repo: https://github.com/marl/medleydb.

**Comment by loretoparisi** [comment]
hey @hugofloresgarcia first thank you for your help.
I'm a bit confused again. I have this setup right now;

<img width="1200" alt="Schermata 2021-11-22 alle 18 16 44" src="https://user-images.githubusercontent.com/163333/142905889-29859fa9-f5be-45b3-9df1-881ad6e48268.png">

File audio are located under `audio/`, while the medleydb library is under `medleydb/`.


```
env: MEDLEYDB_PATH=/home/ec2-user/SageMaker/audio
Global seed set to 42
/home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:64: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  INST_TAXONOMY = yaml.load(fhandle)
/home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:72: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  MIXING_COEFFICIENTS = yaml.load(fhandle)
/home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:94: UserWarning: The medleydb audio was not found at the expected path: None This module will still function, but without the ability to access any of the audio.
  UserWarning
Global seed set to 42
2021-11-22:17:14:44,645 INFO     [seed.py:54] Global seed set to 42
0it [00:00, ?it/s]
```

I have setup the `MEDLEYDB_PATH` to `audio/` where the audio files are located right now:

```
Allegria_MendelssohnMovement1
AmadeusRedux_MozartAllegro
AmadeusRedux_SchubertMovement2
AmadeusRedux_SchubertMovement3
BarefootSisters_RedJetta
CassandraJenkins_PerfectDay
CatMartino_IPromise
Cayetana_MissThing
DahkaBand_SoldierMan
DeadMilkmen_PrisonersCinema
DeclareAString_MendelssohnPianoTrio1Movement1
DeclareAString_MendelssohnPianoTrio1Movement2
FallingSparks_Improvisation1
FallingSparks_Improvisation2
FallingSparks_Improvisation3
...
```

while I'm still getting the error

```
env: MEDLEYDB_PATH=/home/ec2-user/SageMaker/audio
/home/ec2-user/SageMaker/music-trees
Global seed set to 42
/home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:64: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  INST_TAXONOMY = yaml.load(fhandle)
/home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:72: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  MIXING_COEFFICIENTS = yaml.load(fhandle)
/home/ec2-user/SageMaker/medleydb/medleydb/__init__.py:94: UserWarning: The medleydb audio was not found at the expected path: None This module will still function, but without the ability to access any of the audio.
  UserWarning
```

**Comment by hugofloresgarcia** [comment]
it looks like the MedleyDB library needs for the tracks to be located under `${MEDLEYDB_PATH}/Audio`. per https://github.com/marl/medleydb/blob/537bb7bad0601fc58e4fff8404f71658b86ef60e/medleydb/__init__.py#L88
